development:
  adapter: postgresql
  encoding: utf8
  database: carrocaseros
  host: localhost
  pool: 5
  username: carrocaseros
  password: carro.123


production:
  adapter: postgresql
  encoding: utf8
  database: carrocaseros
  pool: 5
  username: carrocaseros
  password: carro.123
